# Generated by Django 5.1.2 on 2024-11-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team_A_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('code_name', models.CharField(max_length=50)),
                ('food_to_bring', models.CharField(max_length=200)),
                ('nabunot', models.CharField(max_length=100)),
            ],
        ),
    ]
