# Generated by Django 5.1.2 on 2024-11-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_team_a_members_team_a_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_A_Member',
            new_name='Team_A_Members',
        ),
    ]
