# Generated by Django 5.1.2 on 2024-11-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_team_a_members_team_a_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_a_member',
            name='code_name',
            field=models.CharField(max_length=50),
        ),
    ]
